theme: jekyll-theme-slate
title: [Clinical Microbiology Flow Charts for Organism Identification]
description: Flow chart guides for the aspiring Laboratory Scientists, and a refresher for those in need.
